### ISSUE TITLE
Ringer doesnt ring the bells

### ISSUE THREAD

**Issue by RobvanSuilen** [sui77/rotary-sim800#1]
Thanks for your amazing code!

One problem I have is that the H-bridge doesnt get high and low signals from my arduino.
The serial monitor does show RingRing but pins 2 and 3 are not controlled.

**Comment by sui77** [comment]
Wow, can't believe someone found this abandoned project :) Attaching the circuit diagram, did you wire it this way?
![20190819_172531](https://user-images.githubusercontent.com/7593527/63278262-44234580-c2a7-11e9-8cb4-0a37d9d8ce4e.jpg)

**Comment by RobvanSuilen** [comment]
Hello Suat,

Wow i didnt expect such a quick reply. Thanks for helping me!
I wired pins 2 and 3 of the arduino UNO to [this](https://opencircuit.nl/Product/10477/L293D-motor-driver-module) board as a test environment. I didnt attach the bell

![L293D-motor-driver-module](https://user-images.githubusercontent.com/54277394/63299239-9aa77880-c2d5-11e9-8e1d-170c373216cc.jpg)

 yet. But each port has a status led that lights up when its HIGH.

Now when I take the code from the fetap 611 and make a program out of it and program the uno with it, the setup works. Code is in the attachment. [fetap611standalone.txt](https://github.com/sui77/rotary-sim800/files/3517664/fetap611standalone.txt)

So I think there is a fault somewhere else in the code. I suspect the use of delays might be the problem. but I'm not nearly experienced enough in arduino to pinpoint the problem.

Thanks for your time!

Sincerely, Rob

**Comment by sui77** [comment]
Delays are ok for a LED to be seen. If you use pin 13 you will see the arduino onboard led blinking. 

Connections to the board should then be:
2 => IN1
3  => IN2 (most likely, if not try IN3, IN4)
5V => VCC
GND => GND
EN1, EN2 => have a jumper or connect to 5V 

Did you connect the higher voltage power source to VCC yet? If not, for testing you can use 5V from Arduino as well, just connect VCC + VIN on the board (but don't forget to disconnect that again before plugging in 35V later).

**Comment by RobvanSuilen** [comment]
Hi Suat,
Did  you you test with pin 13? Because I did and it didnt work.
The problem is not in the hardware or wireing I think. Because it all works when i use the test program I sent you earlier, did you have a look at that?

Attached are two foto's of the H-bridge working with the test program. 
![IMG_20190820_084139_1](https://user-images.githubusercontent.com/54277394/63324337-20ecaa80-c328-11e9-9250-ce906114dbec.jpg)

![IMG_20190820_084134](https://user-images.githubusercontent.com/54277394/63324525-8a6cb900-c328-11e9-93d4-c4a625aabcbd.jpg)

**Comment by RobvanSuilen** [comment]
I found the problem!
It strange but it has to do with the serial communication. 
When I comment

 out lines 6 and 7 that print RINGRING, the H-bridge works.

I dont understand why it works but it does.
![IMG_20190820_090907](https://user-images.githubusercontent.com/54277394/63325560-b12bef00-c32a-11e9-873c-16dd6f18b7f8.jpg)

**Comment by sui77** [comment]
Oh dear, sorry, my fault. It's just the ```return``` instruction, which exits the function and thus skips the rest of the function. I probably put that there in a night session to temporary disable ringing and not waking up my wife and kids :D
